- Entity:
    id: http://www.purl.org/ogit/ITService/Service
    name: Service
    description: |
      A technology service item, which combined or not with other technology services can constitute a service offering.
    admin-contact: arago GmbH
    tech-contact: arago GmbH
    created: 2014-05-27
    creator: FCO
    deleter: 
    modified: 2014-06-12
    parent: http://www.purl.org/ogit/Catalog/Item
    scope: NTO
    valid-from: 2014-06-01
    valid-until: 

    attributes:
      any: true
      mandatory:
        - http://www.purl.org/ogit/ITService/id
        - http://www.purl.org/ogit/uri
      optional:

    history:
      - id: 1
        date: 2014-05-27
        description: 'intitial version'
        modified-by: FCO
      - id: 2
        date: 2014-06-12
        description: 'attribute list updated'
        modified-by: FCO
      - id: 3
        date: 2014-09-05
        description: 'description updated'
        modified-by: Peter Larem
