- Entity:
    id: http://www.purl.org/ogit/ITService/Service
    name: Service
    description: 'a single service template in the catalog'
    admin-contact: 'arago AG'
    tech-contact: 'arago AG'
    created: 2014-05-27
    creator: FCO
    deleter: ''
    modified: 2014-05-27
    parent: http://www.purl.org/ogit/Catalog/Item
    scope: NTO
    valid-from: 2014-06-01
    valid-until: 

    attributes:
      mandatory:
        - http://www.purl.org/ogit/ITService/id
      optional:
        - http://www.purl.org/ogit/ITService/utilizationPercentage

    history:
      - id: 1
        date: 2014-05-27
        description: 'intitial version'
        modified-by: FCO
