- Verb:
    id: http://www.purl.org/ogit/configures
    name: configures
    description: |
      The `from` entity, contains configuration data for the to `entity`
    valid-from: 2015-04-27
    valid-until: 
    creator: cwalker@arago.de
    deleter: 
    created: 2015-04-27
    modified: 2015-04-27
    admin-contact: arago GmbH
    tech-contact: arago GmbH
    hide: 
    cardinality: 
    history:
      - id: 1
        date: 2015-04-27
        description: intitial inception
        modified-by: cwalker@arago.de

    allowed:
      - from: http://www.purl.org/ogit/Forum/Configuration
        to: http://www.purl.org/ogit/Forum/Profile

