- Verb:
    id: http://www.purl.org/ogit/hosts
    name: hosts
    description: |
      verb which shows that an entity is hosted in another entity.
    valid-from: 2015-10-15
    valid-until: 
    creator: Aymen Ayoub
    deleter: 
    created: 2015-10-15
    modified: 2015-10-15
    admin-contact: arago GmbH
    tech-contact: arago GmbH
    hide: 
    cardinality: 
    history:
      - id: 1
        date: 2015-10-15
        description: initial
        modified-by: Aymen Ayoub

    allowed:
      - from: http://www.purl.org/ogit/Automation/MARSNode
        to: http://www.purl.org/ogit/Automation/MARSNode

