- Entity:
    id:   http://www.purl.org/ogit/Software/Application
    name: Application
    description: |
      Represents any type of software application
    valid-from: 2014-11-05 00:00:00
    valid-until:
    creator: PL
    deleter: 
    created:  2014-11-05
    modified: 2014-11-05
    admin-contact: ogit@arago.de
    tech-contact: ogit@arago.de
    scope: NTO
    parent: http://www.purl.org/ogit/Factual
    history:
      - id: 1
        date: 2014-11-05
        description: initial
        modified-by: PL

    attributes:
      any: true
      mandatory:
      optional:
