- Attribute:
    id: http://www.purl.org/ogit/Automation/basicConfigId
    name: basicConfigId
    description: |
      Contains the internal identifier of the basic configuration of a component .
    valid-from: 2015-05-27
    valid-until: 
    creator: Aymen Ayoub
    deleter: 
    created: 2015-07-27
    modified: 2015-07-27
    admin-contact: arago GmbH
    tech-contact: arago GmbH
    validation-type: 
    validation-parameter: 
    history:
      - id: 1
        date: 2015-05-27
        description: initial
        modified-by: Aymen Ayoub
