- Entity:
    id:   http://www.purl.org/ogit/Application
    name: Application
    description: |
      Unlike software assets 'Application' refers to an application which is interacting with A Policy that governs data access in GraphIT. It is connected and applied to Organizations
    valid-from: 2014-08-16 00:00:00
    valid-until:
    creator: arago AG
    deleter: 
    created:  2014-08-15
    modified: 2014-08-15
    admin-contact: ogit@arago.de
    tech-contact: ogit@arago.de
    scope: SGO
    parent: http://www.purl.org/ogit/Global
    history:
      - id: 1
        date: 2014-08-15
        description: initial
        modified-by: FCO

    attributes:
      mandatory:
        - http://www.purl.org/ogit/name
      optional:    
        - http://www.purl.org/ogit/description
        - http://www.purl.org/ogit/function
        - http://www.purl.org/ogit/status
