- Entity:
    id: http://www.purl.org/ogit/ConfigurationItem
    name: ConfigurationItem
    description: |
      A configuration item.
    valid-from: 2015-06-11
    valid-until: 
    creator: Aymen Ayoub
    deleter: 
    created: 2015-06-11
    modified: 2015-06-11
    admin-contact: arago GmbH
    tech-contact: arago GmbH
    scope: SGO
    parent: http://www.purl.org/ogit/Node
    attributes:
      mandatory:
        - http://www.purl.org/ogit/name
      optional:
        - http://www.purl.org/ogit/id
    history:
      - id: 1
        date: 2015-06-11
        description: initial
        modified-by: Aymen Ayoub
      - id: 2
        date: 2015-07-27
        description: updated
        modified-by: Aymen Ayoub
