- Entity:
    id: http://www.purl.org/ogit/ConfigurationItem
    name: ConfigurationItem
    description: |
      A configuration item.
    valid-from: 2015-06-11
    valid-until: 
    creator: Aymen Ayoub
    deleter: 
    created: 2015-06-11
    modified: 2015-06-11
    admin-contact: arago GmbH
    tech-contact: arago GmbH
    scope: SGO
    parent: http://www.purl.org/ogit/Node
    attributes:
      mandatory:
        - http://www.purl.org/ogit/name
      optional:
        - http://www.purl.org/ogit/id
        - http://www.purl.org/ogit/class
        - http://www.purl.org/ogit/type
        - http://www.purl.org/ogit/subType
        - http://www.purl.org/ogit/status
        - http://www.purl.org/ogit/category
        - http://www.purl.org/ogit/priority
        - http://www.purl.org/ogit/impact
        - http://www.purl.org/ogit/isCritical
        - http://www.purl.org/ogit/isSupported
        - http://www.purl.org/ogit/businessCriticality
        - http://www.purl.org/ogit/version
        - http://www.purl.org/ogit/inventoryNumber
        - http://www.purl.org/ogit/invoiceNumber
        - http://www.purl.org/ogit/productOrderNumber
        - http://www.purl.org/ogit/leaseContract
        - http://www.purl.org/ogit/assetTag
        - http://www.purl.org/ogit/pendingChange
        - http://www.purl.org/ogit/faultCount
        - http://www.purl.org/ogit/updateCount
        - http://www.purl.org/ogit/lastUpdatedAt
        - http://www.purl.org/ogit/createdAt
        - http://www.purl.org/ogit/startedAt
        - http://www.purl.org/ogit/installedAt
        - http://www.purl.org/ogit/orderedAt
        - http://www.purl.org/ogit/deliveredAt
        - http://www.purl.org/ogit/purchasedAt
        - http://www.purl.org/ogit/lastScannedAt
        - http://www.purl.org/ogit/endOfWarranty
        - http://www.purl.org/ogit/description
        - http://www.purl.org/ogit/vendor
        - http://www.purl.org/ogit/shortDescription
        - http://www.purl.org/ogit/installStatus
        - http://www.purl.org/ogit/operationalStatus
        - http://www.purl.org/ogit/comment
        - http://www.purl.org/ogit/subCategory
        - http://www.purl.org/ogit/securityClass
        - http://www.purl.org/ogit/soxClass
        - http://www.purl.org/ogit/confidentiality
        - http://www.purl.org/ogit/integrity
        - http://www.purl.org/ogit/availability
        - http://www.purl.org/ogit/contact
        - http://www.purl.org/ogit/serviceContract
        - http://www.purl.org/ogit/assignedAt
        - http://www.purl.org/ogit/checkedInAt
        - http://www.purl.org/ogit/checkedOutAt
        - http://www.purl.org/ogit/content
        - http://www.purl.org/ogit/model
    history:
      - id: 1
        date: 2015-06-11
        description: initial
        modified-by: Aymen Ayoub
      - id: 2
        date: 2015-07-27
        description: updated
        modified-by: Aymen Ayoub
      - id: 3
        date: 2015-08-17
        description: updated
        modified-by: Peter Larem
      - id: 4
        date: 2015-08-19
        description: updated
        modified-by: Aymen Ayoub
