- Entity:
    id:   http://www.purl.org/ogit/CustomApplicationData
    name: CustomApplicationData
    description: |
      Entity to store custom application data.
    valid-from: 2013-11-01 00:00:00
    valid-until:
    creator: Peter Larem
    deleter: 
    created:  2013-09-01
    modified: 2013-09-01
    admin-contact: arago AG
    tech-contact: arago AG
    scope: SGO
    conforms-to:
    parent: http://www.purl.org/ogit/Factual

    attributes:
      any: true
      mandatory:
      optional:

    history:
      - id: 1
        date: 2013-09-01
        description: initial
        modified-by: Peter Larem
      - id: 2
        date: 2014-06-08
        description: allow any attribute
        modified-by: FCO

