- Entity:
    id: http://www.purl.org/ogit/Schema
    name: Schema
    description: Any type of schema, could be defined in XSD, YAML, etc.
    scope: NTO
    valid-from: '2015-05-19'
    valid-until: ''
    creator: Peter Larem
    deleter: ''
    created: '2015-05-19'
    modified: '2015-05-19'
    admin-contact: arago GmbH
    tech-contact: arago GmbH
    parent: http://www.purl.org/ogit/Node
    history:
    - {id: 1, description: initial, modified-by: Peter Larem, date: '2015-05-19'}
    attributes:
      mandatory: ['http://www.purl.org/ogit/uri', 'http://www.purl.org/ogit/name']
