- Entity:
    id: http://www.purl.org/ogit/Schema
    name: Schema
    description: |
      Any type of schema, could be defined in XSD, YAML, etc.
    valid-from: 2015-05-21
    valid-until: 
    creator: Peter Larem
    deleter: 
    created: 2015-05-21
    modified: 2015-05-21
    admin-contact: arago GmbH
    tech-contact: arago GmbH
    scope: SGO
    parent: http://www.purl.org/ogit/Node
    attributes:
      mandatory:
        - http://www.purl.org/ogit/content
      optional:
        - http://www.purl.org/ogit/uri
        - http://www.purl.org/ogit/name
    history:
      - id: 1
        date: 2015-05-21
        description: initial
        modified-by: Peter Larem
