- Entity:
    id:   http://www.purl.org/arago/view/App
    name: App
    description: |
      An app that can be used to view OGIT content
    valid-from: 2013-11-01 00:00:00
    valid-until:
    creator: SP
    deleter: 
    created:  2014-11-26
    modified: 2014-11-26
    admin-contact: arago AG
    tech-contact: arago AG
    scope: NTO
    parent: http://www.purl.org/ogit/Factual
    history:
      - id: 1
        date: 2014-11-26
        description: initial
        modified-by: SP
      
    attributes:
      mandatory:
        - http://www.purl.org/ogit/name
        - http://www.purl.org/ogit/description
        - http://www.purl.org/ogit/version
      optional:
        - http://www.purl.org/ogit/url
