- Entity:
    id:   "MARSApplicationNode"
    name: "MARSApplicationNode"
    description: "ApplicationNode provides functions to user or business process, ApplicationNode exists of one or more SoftwareNodes"
    valid-from: "2013-11-01 00:00:00"
    valid-until: "2014-11-01 00:00:00"
    creator: ""
    deleter: ""
    created:  "2013-09-01"
    modified: "2013-09-01"
    admin-contact: ""
    tech-contact: ""
    scope: "NTO"
    url: ""
    schema: "AutoPilotMARSSchema2013"
    parent: "MARSNode"
    history:
      - id: 1
        date: "2013-09-01"
        description: "initial"
        modified-by: ""

    attributes:
      mandatory:
      optional:
