- Entity:
    id:   http://www.purl.org/arago/MARSApplicationNode
    name: MARSApplicationNode
    description: |
      An application node provides functions to the user or a business process, bundling one or more resource nodes.
      Example: A CRM consisting of a CRM resource and a webserver resource for mobile access.
    valid-from: 2013-11-01 00:00:00
    valid-until:
    creator: Peter Larem
    deleter: 
    created:  2013-09-01
    modified: 2013-09-01
    admin-contact: arago AG
    tech-contact: arago AG
    scope: NTO
    parent: http://www.purl.org/arago/MARSNode
    history:
      - id: 1
        date: 2013-09-01
        description: initial
        modified-by: Peter Larem

    attributes:
      any: true
      mandatory:
      optional:
