- Entity:
    id:   http://www.purl.org/arago/AutoPilot_MARS/entities/MARSApplicationNode
    name: MARSApplicationNode
    description: |
      An application node provides functions to the user or a business process, bundling one or more resource nodes.
      Example: A CRM consisting of a CRM resource and a webserver resource for mobile access.
    valid-from: 2013-11-01 00:00:00
    valid-until: 2014-11-01 00:00:00
    creator: 
    deleter: 
    created:  2013-09-01
    modified: 2013-09-01
    admin-contact: 
    tech-contact: 
    scope: NTO
    url: 
    schema: AutoPilotMARSSchema2013
    parent: http://www.purl.org/arago/AutoPilot_MARS/entities/MARSNode
    history:
      - id: 1
        date: 2013-09-01
        description: initial
        modified-by: 

    attributes:
      mandatory:
      optional:
