- Entity:
    id: http://www.purl.org/ogit/ServiceManagement/Action
    name: Action
    description: |
      Defines Actions on it Services. A Service is connected to the available Actions by the "supports" relationship.
    valid-from: 2015-05-21
    valid-until: 
    creator: Peter Larem
    deleter: 
    created: 2015-05-21
    modified: 2015-05-21
    admin-contact: arago GmbH
    tech-contact: arago GmbH
    scope: NTO
    parent: http://www.purl.org/ogit/Node
    attributes:
      mandatory:
        - id: http://www.purl.org/ogit/name
      optional:
        - id: http://www.purl.org/ogit/id
        - id: http://www.purl.org/ogit/description
    history:
      - id: 1
        date: 2015-05-21
        description: initial
        modified-by: Peter Larem
