- Entity:
    id: http://www.purl.org/ogit/ServiceManagement/Action
    name: Action
    description: Defines Actions on it Services. A Service is connected to the available Actions by the "supports" relationship.
    scope: NTO
    valid-from: '2015-05-19'
    valid-until: ''
    creator: Peter Larem
    deleter: ''
    created: '2015-05-19'
    modified: '2015-05-19'
    admin-contact: arago GmbH
    tech-contact: arago GmbH
    parent: http://www.purl.org/ogit/Node
    history:
    - {id: 1, description: initial, modified-by: Peter Larem, date: '2015-05-19'}
    attributes:
      mandatory: ['http://www.purl.org/ogit/id', 'http://www.purl.org/ogit/description']
