- Entity:
    id: http://www.purl.org/ogit/ServiceManagement/Service
    name: Service
    description: A technology service item, which combined or not with other technology services can constitute a service offering (ogit/ServiceManagement/Offering).
    scope: NTO
    valid-from: '2015-05-19'
    valid-until: ''
    creator: Peter Larem
    deleter: ''
    created: '2015-05-19'
    modified: '2015-05-19'
    admin-contact: arago GmbH
    tech-contact: arago GmbH
    parent: http://www.purl.org/ogit/Node
    history:
    - {id: 1, description: initial, modified-by: Peter Larem, date: '2015-05-19'}
    attributes:
      mandatory: ['http://www.purl.org/ogit/description', 'http://www.purl.org/ogit/name',
        'http://www.purl.org/ogit/id', 'http://www.purl.org/ogit/uri']
