- Entity:
    id: http://www.purl.org/ogit/ServiceManagement/Service
    name: Service
    description: |
      A technology service item, which combined or not with other technology services can constitute a service offering (ogit/ServiceManagement/Offering).
    valid-from: 2015-05-21
    valid-until: 
    creator: Peter Larem
    deleter: 
    created: 2015-05-21
    modified: 2015-05-21
    admin-contact: arago GmbH
    tech-contact: arago GmbH
    scope: NTO
    parent: http://www.purl.org/ogit/Node
    attributes:
      optional:
        - http://www.purl.org/ogit/description
        - http://www.purl.org/ogit/name
        - http://www.purl.org/ogit/id
        - http://www.purl.org/ogit/uri
    history:
      - id: 1
        date: 2015-05-21
        description: initial
        modified-by: Peter Larem
