- Entity:
    id:   http://www.purl.org/ogit/Schema
    name: Schema
    description: |
      A schema within graphit.
    valid-from: 2013-11-01 00:00:00
    valid-until: 2014-11-01 00:00:00
    creator: 
    deleter: 
    created:  2013-11-01
    modified: 2013-11-01
    admin-contact: 
    tech-contact: 
    scope: SGO
    url: 
    parent: http://www.purl.org/ogit/Global
    history:
      - id: 1
        date: 2013-11-01
        description: initial
        modified-by: 

    attributes:
      mandatory:
      optional:    
