- Entity:
    id:   http://www.purl.org/ogit/Schema
    name: Schema
    description: |
      A schema within graphit.
    valid-from: 2013-11-01 00:00:00
    valid-until:
    creator: arago GmbH
    deleter: 
    created:  2013-11-01
    modified: 2014-03-27
    admin-contact: ogit@arago.de
    tech-contact: ogit@arago.de
    scope: SGO
    parent: http://www.purl.org/ogit/Global
    history:
      - id: 1
        date: 2013-11-01
        description: initial
        modified-by: Peter Larem
      - id: 2
        date: 2014-03-27
        description: attributes URI, content added
        modified-by: fotto
      - id: 3
        date: 2014-04-14
        description: attribute information added
        modified-by: FCO

    attributes:
      mandatory:
        - http://www.purl.org/ogit/uri
        - http://www.purl.org/ogit/content
      optional:    
        - http://www.purl.org/ogit/information
